sudo: required
services:
  - docker
before_install:
  - docker build -t ranjani4/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ranjani4/react-test npm test
after-success:
  - docker build -t ranjani4/multi-client ./client
  - docker build -t ranjani4/multi-nginx ./nginx
  - docker build -t ranjani4/multi-server ./server
  - docker build -t ranjani4/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the built images and push to docker hub
  - docker push ranjani4/multi-client
  - docker push ranjani4/multi-nginx
  - docker push ranjani4/multi-server
  - docker push ranjani4/multi-worker
